apiVersion: apps/v1
kind: Deployment
metadata:
  name: specialization-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: specializationservice
  template:
    metadata:
      labels:
        app: specializationservice
    spec:
      containers:
        - name: specializationservice
          image: wjarod/specializationservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: specialization-clusterip-server
spec:
  type: ClusterIP
  selector:
    app: specializationservice
  ports:
    - name: specializationservice
      protocol: TCP
      port: 80
      targetPort: 80